---
title: "Demanda de tomate"
author: "Luis Fernando Delgado Muñoz"
date: "22/3/2022"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = F,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
```


# Carga de datos

```{r}
library(readr)
tomate <- read_delim("../Demanda_tomate/Datos_tomate.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

knitr::kable(tomate)
```

# Tidy data

```{r}
tomate <- tomate %>% pivot_longer(c("Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"), names_to = "Dias_semana", values_to = "Demanda")

tomate$Semana = as.factor(tomate$Semana)

```

```{r fig.align='center', fig.width= 12, fig.height= 10}
tomate %>% 
  ggplot(aes(x = reorder(Dias_semana, Demanda), y = Demanda)) +
  #facet_wrap(~Semana) +
  geom_boxplot(aes(fill = Dias_semana)) +
  geom_jitter(width = 0.2, size = 2) +
  theme_bw() +
  labs(x = "Días", y = "Demanda (t)", title = "Demanda de tomate semanal por 30 semanas") 
```

```{r fig.align='center', fig.width= 12, fig.height= 10}
tomate %>% 
  ggplot(aes(x = reorder(Dias_semana, Demanda), y = Demanda)) +
  facet_wrap(~Semana) +
  geom_jitter(aes(shape = Dias_semana), size = 3) +
  scale_shape_manual(values=c(1:7)) +
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1 , angle = 90)) +
  labs(x = "Días", y = "Demanda (t)", title = "Demanda de tomate semanal por 30 semanas") 
```
```{r fig.align='center', fig.width= 12, fig.height= 10}
tomate_se <- tomate %>% group_by(Semana) %>% summarize(n = n(),
         mean = mean(Demanda),
         sd = sd(Demanda),
         se = sd / sqrt(n),
         ci = qt(0.975, df = n - 1) * sd / sqrt(n))  

knitr::kable(tomate_se %>% select(-c(n, se, ci)))
```

```{r fig.align='center', fig.width= 12, fig.height= 10}
tomate_se %>% ggplot(aes(x = reorder(Semana, mean),
           y = mean,
           group = 1)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = mean - se,
                    ymax = mean + se),
                width = .1) +
  theme_bw() +
  labs(x = "Semana", y = "Promedio de demanda (t)")
```
# Carga de datos de salchichas

```{r}
salchichas <- read.csv("../Demanda_tomate/Salchichas.csv", header=TRUE, sep=";")

salchichas$Maquina <- factor(salchichas$Maquina,
                              labels = c("Maquina 1",
                                         "Maquina 2"))
salchichas_wider <- salchichas %>%
  group_by(Maquina) %>%
  mutate(row = row_number()) %>% pivot_wider(names_from = Maquina, values_from = Peso) %>%  select(-row)

knitr::kable(salchichas_wider)
```

```{r fig.align='center', fig.width= 10, fig.height= 8}
salchichas$Interaccion <- paste(salchichas$Operario,salchichas$Maquina, sep=":")

ggplot(salchichas, aes(x = Interaccion, y = Peso, fill = Interaccion)) +
        geom_boxplot() +
        geom_jitter(color = "black", width = 0.1, alpha = 0.3) +
        theme_bw() +
        labs(x = "Interacción entre operarios y embutidoras", 
             y = "Peso salchichas (g)", 
             title = "Pesos de salchichas en función de operarios y embutidoras") +
        geom_hline(yintercept = c(210, 230), linetype = "dotted", 
                   color = "red", size = 2)
```




